version: "3.9"

services:
  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  celery:
    build: .
    command: celery -A reminder_project worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - app

  celery-flower:
    build: .
    command: celery -A reminder_project flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
