# Generated by Django 5.2.7 on 2025-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
